version: '3.8'

services:
  orchestrator:
    build:
      context: .
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - '${DB_PORT}:5432'

volumes:
  pgdata:
